"""Command line interface for the supported package workflow."""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import typer
from rich.console import Console

from fairness_project.config import load_config
from fairness_project.data.preprocess import prepare_model_ready_data
from fairness_project.experiment import ExperimentResult, run_experiment
from fairness_project.governance.gate import check_gate, load_report
from fairness_project.inference.batch import run_batch_inference
from fairness_project.inference.service import InferenceService

app = typer.Typer(
    name="fairness",
    help="Leakage-free responsible-ML audit tools for the UCI Adult example.",
    add_completion=False,
    no_args_is_help=True,
)
data_app = typer.Typer(help="Prepare the bundled UCI Adult data.", no_args_is_help=True)
app.add_typer(data_app, name="data")
console = Console()


def audit_command(
    *,
    model: Literal["lr", "rf", "xgb"],
    seed: int,
    data_path: Path,
    output_dir: Path,
    run_id: str | None,
    config_path: Path | None,
    bootstrap_samples: int,
) -> ExperimentResult:
    """Execute the canonical experiment path without CLI-specific side effects."""
    config = load_config(config_path)
    return run_experiment(
        data_path=data_path,
        output_dir=output_dir,
        model_type=model,
        seed=seed,
        val_ratio=config.data.val_size,
        run_id=run_id,
        config=config,
        bootstrap_samples=bootstrap_samples,
    )


@app.command()
def audit(
    model: Literal["lr", "rf", "xgb"] = typer.Option("xgb", help="Model benchmark."),
    seed: int = typer.Option(42, min=0, help="Split and estimator seed."),
    data_path: Path = typer.Option(
        Path("data/processed/adult/adult_model_ready.csv"),
        exists=True,
        dir_okay=False,
        help="Model-ready Adult CSV.",
    ),
    output_dir: Path = typer.Option(Path("runs"), help="Parent directory for run bundles."),
    run_id: str | None = typer.Option(None, help="Stable run identifier; generated by default."),
    config_path: Path | None = typer.Option(
        None,
        "--config",
        exists=True,
        dir_okay=False,
        help="Optional YAML configuration.",
    ),
    bootstrap_samples: int = typer.Option(
        500,
        min=0,
        help="Paired stratified bootstrap replicates; 0 disables intervals.",
    ),
    require_gate_pass: bool = typer.Option(
        False,
        help="Exit non-zero when the experimental policy gate fails.",
    ),
) -> None:
    """Train one model, tune on validation, evaluate on test, and save one bundle."""
    result = audit_command(
        model=model,
        seed=seed,
        data_path=data_path,
        output_dir=output_dir,
        run_id=run_id,
        config_path=config_path,
        bootstrap_samples=bootstrap_samples,
    )
    verdict = "PASSED" if result.gate.passed else "FAILED"
    style = "bold green" if result.gate.passed else "bold yellow"
    console.print(f"Run bundle: {result.run_dir}")
    console.print(f"Experimental policy gate: {verdict}", style=style)
    for violation in result.gate.violations:
        console.print(f"  - {violation}")
    if not result.gate.report_valid:
        raise typer.Exit(code=2)
    if require_gate_pass and not result.gate.passed:
        raise typer.Exit(code=result.gate.exit_code)


@app.command("gate")
def gate_report(
    report: Path = typer.Option(..., exists=True, dir_okay=False, help="Evaluation report."),
) -> None:
    """Check one versioned report against the default experimental policy."""
    try:
        result = check_gate(load_report(report))
    except (OSError, ValueError) as exc:
        console.print("Governance Gate: ERROR", style="bold red")
        console.print(f"  - {exc}")
        raise typer.Exit(code=2) from None

    if result.report_valid:
        status = "PASSED" if result.passed else "FAILED"
    else:
        status = "ERROR"
    console.print(f"Governance Gate: {status}")
    for violation in result.violations:
        console.print(f"  - {violation}")
    if result.exit_code:
        raise typer.Exit(code=result.exit_code)


@app.command()
def predict(
    run_dir: Path = typer.Option(..., exists=True, file_okay=False, help="Validated run bundle."),
    input_csv: Path = typer.Option(..., exists=True, dir_okay=False, help="Input CSV."),
    output_csv: Path = typer.Option(..., dir_okay=False, help="Prediction output CSV."),
) -> None:
    """Run baseline batch inference from a validated bundle."""
    service = InferenceService.from_run(run_dir)
    run_batch_inference(service=service, input_path=input_csv, output_path=output_csv)
    console.print(f"Predictions saved to {output_csv}", style="bold green")


@data_app.command("preprocess")
def preprocess_data(
    input_dir: Path = typer.Option(Path("data/raw/adult"), exists=True, file_okay=False),
    output_path: Path = typer.Option(
        Path("data/processed/adult/adult_model_ready.csv"),
        dir_okay=False,
    ),
) -> None:
    """Rebuild the model-ready CSV from the bundled raw train/test files."""
    prepare_model_ready_data(
        train_path=input_dir / "adult.data",
        test_path=input_dir / "adult.test",
        output_path=output_path,
    )


def main() -> None:
    app()


if __name__ == "__main__":
    main()
